cetacean_incidents/apps/contacts/urls.py
from django.conf.urls.defaults import patterns

from models import Contact
import views

contacts_args = {
    'queryset': Contact.objects.all(),
    'template_object_name': 'contact',
}

urlpatterns = patterns('cetacean_incidents.generic_views',
    (r'^$', 'object_list', contacts_args, 'all_contacts'),
)

urlpatterns += patterns('',
    (r'^(?P<contact_id>\d+)/$', views.contact_detail, {}, 'contact_detail'),
    (r'^create$', views.create_contact, {}, 'create_contact'),
    (r'^(\d+)/edit$', views.edit_contact, {}, 'edit_contact'),
    (
        r'^(?P<destination_id>\d+)/merge$',
        views.merge_contact,
        {},
        'merge_contact',
    ),
    (
        r'^(?P<destination_id>\d+)/merge/(?P<source_id>\d+)$',
        views.merge_contact,
        {},
        'merge_contact',
    ),
    (r'^search$', views.contact_search, {}, 'contact_search'),
)


cetacean_incidents/urls.py
from django.conf import settings
from django.conf.urls.defaults import *

from django.contrib import admin

from reversion.models import Revision

from generic_views import direct_to_template
import views

admin.autodiscover()

urlpatterns = patterns('',
    # docs needs to come first, or else the admin site will match
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    
    (r'^contacts/', include('cetacean_incidents.apps.contacts.urls')),
    (r'^taxons/', include('cetacean_incidents.apps.taxons.urls')),
    (r'^documents/', include('cetacean_incidents.apps.documents.urls')),
    (r'^incidents/', include('cetacean_incidents.apps.incidents.urls')),
    (r'^csv_import/', include('cetacean_incidents.apps.csv_import.urls')),
    (r'^entanglements/', include('cetacean_incidents.apps.entanglements.urls')),
    (r'^shipstrikes/', include('cetacean_incidents.apps.shipstrikes.urls')),
    (r'^tags/', include('cetacean_incidents.apps.tags.urls')),
    
    (r'^manual/', include('cetacean_incidents.apps.manual.urls')),
    (r'^problems/', views.odd_entries, {}, 'odd_entries'),
 
    # strip the initial '/' from the login url
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
    # the permission_required decorator redirects on bad permissions
    url(r'^not_allowed/$', direct_to_template, {'template': 'not_allowed.html'}, 'not_allowed'),
    
    (r'^clear_cache/', views.clear_cache, {}, 'clear_cache'),
    
    (r'^$', views.home, {}, "home")
)

all_revisions_args = {
    'queryset': Revision.objects.all().order_by('-date_created'),
    'template_object_name': 'rev',
}
recent_revisions_args = {
    'queryset': Revision.objects.all().order_by('-date_created')[:20],
    'template_object_name': 'rev',
}
urlpatterns += patterns('cetacean_incidents.generic_views',
    (r'^revisions/$', 'object_list', all_revisions_args, 'all_revisions'),
    (r'^revisions/recent$', 'object_list', recent_revisions_args, 'recent_revisions'),
)
urlpatterns += patterns('',
    (r'^new_case$', views.new_case, {}, 'new_case'),
    (r'^revisions/(?P<rev_id>\d+)/$', views.revision_detail, {}, 'revision_detail'),
    (r'^revisions/object_history/(?P<content_type_id>\d+)/$', views.object_history, {}, 'object_history'),
    (r'^revisions/object_history/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$', views.object_history, {}, 'object_history'),
    
    (r'staff_tools/import_taxon$', views.import_taxon, {}, 'import_taxon'),
)

# name the MEDIA_URL for use in templates. also has django serve up media if
# the hosting webserver doesn't.
urlpatterns += patterns("django.views",
    # strip URL_PREFIX from MEDIA_URL
    url(r"^%s(?P<path>.*)$" % settings.MEDIA_URL[len(settings.URL_PREFIX):],
        "static.serve",
        {"document_root": settings.MEDIA_ROOT},
        name="site-media",
    ),
)

# we re-use some widgets from the admin interface which expect this
js_info_dict = {
    'packages': ('django.conf',),
}
urlpatterns += patterns('django.views',
    (r'^jsi18n/$', 'i18n.javascript_catalog', js_info_dict, 'jsi18n'),
)

from django.contrib import databrowse
from cetacean_incidents.apps.taxons.models import Taxon
from cetacean_incidents.apps.incidents.models import Animal
from cetacean_incidents.apps.entanglements.models import Entanglement, EntanglementObservation

databrowse.site.register(Animal)
databrowse.site.register(Taxon)
databrowse.site.register(Entanglement)
databrowse.site.register(EntanglementObservation)

urlpatterns += patterns('',
    (r'^databrowse/(.*)', databrowse.site.root),
)

cetacean_incidents/apps/contacts/models.py
from django.db import models
from django.db.models import Q

from cetacean_incidents.apps.clean_cache import (
    CacheDependency,
    TestList,
)

from cetacean_incidents.apps.documents.models import Documentable

class Organization(models.Model):
    
    name = models.CharField(
        max_length= 1023,
    )
    
    class Meta:
        ordering = ('name',)
    
    def __unicode__(self):
        return self.name

class AbstractContact(models.Model):
    # This exists so GearOwner can inherit all the fields from Contact but keep
    # them in a separate table.

    name = models.CharField(
        max_length= 1023,
        blank= True,
        null= True,
        help_text= u"The contact's name.",
    )
    person = models.NullBooleanField(
        blank= True,
        null= True,
        default= True,
        help_text= u"Is this a person? (i.e. not an organization)",
    )
    
    phone = models.CharField(
        max_length= 255,
        blank= True,
        verbose_name= "phone number",
    )
    
    email = models.EmailField(
        blank= True,
        verbose_name= "email address",
    )
    
    address = models.TextField(
        max_length= 1023,
        blank= True,
        help_text= "mailing address",
    )
    
    notes = models.TextField(
        blank= True,
        help_text= u"""Anything to note about this contact info? e.g. office 
            hours, alternative phone numbers, etc.""",
    )
    
    def __unicode__(self):
        if self.name:
            return self.name
        
        if self.pk:
            return "<unnamed contact> (#%06d)" % self.pk
            
        return "<unnamed contact> (unsaved)"

    class Meta:
        abstract = True

class Contact(AbstractContact, Documentable):
    """\
    A contact is a name of a person _or_ organization, preferably with some
    way of contacting them. 
    
    Note that only one each of phone, email, etc. is given so that contacts
    just have a primary phone or email to contact them at. Other ones could be
    noted in the 'notes' field, if necessary.

    """

    # should default to name. see save() func below
    sort_name = models.CharField(
        max_length= 1023,
        blank= True,
        help_text= u"""\
            Used in sorting contacts. If left blank, will be filled in with the
            same value as 'name'.
        """,
    )

    # TODO properties probably shouldn't do queries
    @property
    def observed_ordered(self):
        return self.observed.order_by(
            'datetime_observed',
            'datetime_reported',
        )

    # TODO properties probably shouldn't do queries
    @property
    def reported_ordered(self):
        return self.reported.order_by(
            'datetime_reported',
            'datetime_observed',
        )
    
    def observed_or_reported_ordered(self):
        observed = Q(observer= self)
        reported = Q(reporter= self)
        # doing this here avoids circular imports
        from cetacean_incidents.apps.incidents.models import Observation
        return Observation.objects.filter(observed | reported).order_by(
            'datetime_observed',
            'datetime_reported',
        )

    affiliations = models.ManyToManyField(
        Organization,
        related_name = 'contacts',
        blank= True,
        null= True,
        help_text= u"""The organization(s) that this contact is affilitated
            with, if any. For contacts that are themselves organizations, give
            a more general org. that they're part of, if any. (e.g. 'Coast
            Guard'). The idea is to track indivdual people or orgs (whichever
            makes more sense as a contact for a particular observation), but
            still group them into sets. For example, a contact might be for the
            Boston Coast Guard office, but it would have a 'Coast Guard'
            affiliation, so that one could easily answer questions like "How
            many reports did we get from the Coast Guard last year?"
        """,
    )

    def clean(self):
        # TODO using validation method to fill in default
        # TODO make 'sort_name' blank in the interface if it's the same as name
        if not self.sort_name:
            self.sort_name = self.name
    
    def get_html_options(self):
        options = super(Contact, self).get_html_options()
        
        # AbstractContact.__unicode__ uses name
        if not 'cache_deps' in options:
            options['cache_deps'] = CacheDependency()
        options['cache_deps'] = CacheDependency(
            update= {self: TestList([True])},
            delete= {self: TestList([True])},
        )
        
        return options
    
    @models.permalink
    def get_absolute_url(self):
        return ('contact_detail', [str(self.pk)]) 
    
    class Meta:
        ordering = ('sort_name', 'name', 'documentable_ptr')


cetacean_incidents/apps/tags/models.py
from django.db import models

from django.contrib.auth.models import User

from cetacean_incidents.apps.delete_guard import guard_deletes

from cetacean_incidents.apps.documents.models import Documentable

class Tag(models.Model):
    
    entry = models.ForeignKey(
        Documentable,
    )
    
    user = models.ForeignKey(
        User,
    )
    
    datetime_tagged = models.DateTimeField(
        auto_now_add=True,
    )
    
    tag_text = models.CharField(
        db_index=True,
        max_length=1024,
    )

    def __unicode__(self):
        return u"tag on %s: \u201c%s\u201d" % (self.entry.specific_instance(), self.tag_text)

# Allow deletion of a Documentable to casecade to Tags view Tags.entry
guard_deletes(User, Tag, 'user')

cetacean_incidents/apps/contacts/views.py
from django.conf import settings
from django.core.paginator import (
    Paginator,
    InvalidPage,
    EmptyPage,
)
from django.forms import Media
from django.shortcuts import (
    redirect,
    render_to_response,
)
from django.template import RequestContext
from django.views.decorators.http import condition

from django.contrib.auth.decorators import login_required

from cetacean_incidents.decorators import (
    permission_required,
    global_etag,
)
from cetacean_incidents.forms import (
    merge_source_form_factory,
    PagingForm,
)

from forms import (
    ContactForm,
    ContactMergeForm,
    ContactSearchForm,
)
from models import Contact

@login_required
def contact_detail(request, contact_id):
    
    contact = Contact.objects.get(pk=contact_id)
    
    template_media = Media(js=(settings.JQUERY_FILE,))
    
    context = {
        'contact': contact,
        'media': template_media,
    }

    if request.user.has_perms((
        'contacts.change_contact',
        'contacts.delete_contact',
    )):
        merge_form = merge_source_form_factory(Contact, contact)()
        context['media'] += merge_form.media
        context['merge_form'] = merge_form
    
    return render_to_response(
        'contacts/contact_detail.html',
        context,
        context_instance= RequestContext(request),
    )

@login_required
def _create_or_edit_contact(request, contact_id=None):
    # assme user has contacts.add_contact and contacts.change_contact
    if not contact_id is None:
        # we're editing an existing contact
        contact = Contact.objects.get(pk=contact_id)
        template = 'contacts/edit_contact.html'
    else:
        # we're creating a new contact
        contact = None # the default for ContactForm(instance=)
        template = 'contacts/create_contact.html'
    
        
    if request.method == 'POST':
        form = ContactForm(request.POST, instance=contact)
        if form.is_valid():
            contact = form.save()
            return redirect('contact_detail', contact.pk)
    else:
        form = ContactForm(instance=contact)
    
    media = form.media
    
    context = {
        'contact': contact,
        'form': form,
        'media': media,
    }
    
    return render_to_response(
        template,
        context,
        context_instance= RequestContext(request),
    )

@login_required
@permission_required('contacts.add_contact')
def create_contact(*args, **kwargs):
    return _create_or_edit_contact(*args, **kwargs)

@login_required
@permission_required('contacts.change_contact')
def edit_contact(*args, **kwargs):
    return _create_or_edit_contact(*args, **kwargs)

@login_required
@permission_required('contacts.change_contact')
@permission_required('contacts.delete_contact')
def merge_contact(request, destination_id, source_id=None):
    # the "source" contact will be deleted and references to it will be changed
    # to the "destination" contact
    
    destination = Contact.objects.get(pk=destination_id)

    if source_id is None:
        merge_form = merge_source_form_factory(Contact, destination)(request.GET)

        if not merge_form.is_valid():
            return redirect('contact_detail', destination.pk)
        source = merge_form.cleaned_data['source']
    else:
        source = Contact.objects.get(pk=source_id)
    
    form_kwargs = {
        'source': source,
        'destination': destination,
    }
    
    if request.method == 'POST':
        form = ContactMergeForm(data=request.POST, **form_kwargs)
        if form.is_valid():
            form.save()
            form.delete()
            return redirect('contact_detail', destination.pk)
    else:
        form = ContactMergeForm(**form_kwargs)
    
    return render_to_response(
        'contacts/merge_contact.html',
        {
            'object_name': 'contact',
            'object_name_plural': 'contacts',
            'destination': destination,
            'source': source,
            'form': form,
            'media': form.media,
        },
        context_instance= RequestContext(request),
    )

@login_required
@condition(etag_func=global_etag)
def contact_search(request):

    form_kwargs = {}
    if request.GET:
        form_kwargs['data'] = request.GET
    form = ContactSearchForm(**form_kwargs)
    paging_form = PagingForm(prefix='paging', **form_kwargs)
        
    contact_list = tuple()
    
    if form.is_valid():
        contact_list = form.results()
        
    per_page = 1
    page = 1
    if paging_form.is_valid():
        if 'per_page' in paging_form.cleaned_data:
            per_page = paging_form.cleaned_data['per_page']
        if 'page_num' in paging_form.cleaned_data:
            page = paging_form.cleaned_data['page_num']

    paginator = Paginator(contact_list, per_page)

    try:
        contacts = paginator.page(page)
    except (EmptyPage, InvalidPage):
        contacts = paginator.page(paginator.num_pages)
    
    template_media = Media(js=(settings.JQUERY_FILE,))
    
    return render_to_response(
        "contacts/contact_search.html",
        {
            'form': form,
            'paging_form': paging_form,
            'media': template_media + form.media,
            'contacts': contacts,
            'contact_count': paginator.count,
        },
        context_instance= RequestContext(request),
    )

cetacean_incidents/templates/contacts/change_contact_include.html
{# assumes a ContactForm named 'form' #}
<table class="layout">
    <tr class="layout">
        <td class="layout">
            {% if form.non_field_errors %}
            {{ form.non_field_errors }}
            {% endif %}
            <div class="subform">
                <h3>Contact Info</h3>
                {% with form.name as f %}
                {% include "labeled_field.html" %}
                {% endwith %}
                {% with form.sort_name as f %}
                {% include "labeled_field.html" %}
                {% endwith %}
                {% with form.person as f %}
                {% include "labeled_field.html" %}
                {% endwith %}
                {% with form.phone as f %}
                {% include "labeled_field.html" %}
                {% endwith %}
                {% with form.email as f %}
                {% include "labeled_field.html" %}
                {% endwith %}
                {% with form.address as f %}
                {% include "labeled_field.html" %}
                {% endwith %}
                {% with form.notes as f %}
                {% include "labeled_field.html" %}
                {% endwith %}
            </div>
        </td>
        <td class="layout">
            <div class="subform">
                <h3>Contact Affiliations</h3>
                {% with form.affiliations as f %}
                {% include "unlabeled_field.html" %}
                {% endwith %}
                {% if perms.contacts.add_organization %}
                <div>
                    <span class="fieldname">add new organizations to be affiliated with:</span>
                    <table>
                        {{ form.new_affs.as_table }}
                    </table>
                </div>
                {% endif %}
            </div>
        </td>
    </tr>
</table>

cetacean_incidents/templates/contacts/contact_base.html
{% extends "detail.html" %}
{% load generic_field_display %}
{% load observation_extras %} {# for datetime_observed_display #}
{% load link_filter %}
{% load html_filter %}

{% block head %}
{{ block.super }}
<script type="text/javascript" src="{% url site-media path="sorttable/sorttable.js" %}"></script>
<link rel="stylesheet" type="text/css" href="{% url site-media path="sorttable/sorttable.css" %}">
{% endblock %}


{% block ids-dl %}
<dt><b>contact</b> local ID</dt><dd>{{ contact.id }}</dd>
{% endblock %}

{% block header %}
<div>
    <h2>{{ contact|html }}</h2>
</div>
{% with contact.tag_set.all as tags %}
{% include "tags/tags_detail_include.html" %}
{% endwith %}
{% endblock %}

{% block content %}
{% block contact_fields %}
<table class="layout">
    <tr class="layout">
        <td class="layout" style="width:50%;">
            <table class="section">
                {% display_row contact "name" %}
                {% display_yesnounk_row contact "person" "person, or organization?" "person,organization,unknown" %}
                {% if contact.phone %}
                {% display_row contact "phone" %}
                {% endif %}
                {% if contact.email %}
                {% display_row contact "email" %}
                {% endif %}
                {% if contact.address %}
                {% display_bigtext_row contact "address" %}
                {% endif %}
                {% display_bigtext_row contact "notes" %}
            </table>
        </td>
        <td class="layout" style="width:50%;">
            <div class="section">
                <h3>Affiliations</h3>
                {% if contact.affiliations.count %}
                <ul>
                    {% for o in contact.affiliations.all %}
                    <li>{{ o|html }}</li>
                    {% endfor %}
                </ul>
                {% else %}
                <i>none</i>
                {% endif %}
            </div>
        </td>
    </tr>
</table>
{% endblock %}
<div class="section">
    <div>
        <h3>Observations reported or observed</h3>
        {% if contact.observed.count or contact.reported.count %}
        <table class="sortable">
            <thead>
                <tr>
                    <th class="sorttable_nosort">&nbsp;</th>
                    <th>observer</th>
                    <th>date observed</th>
                    <th>reporter</th>
                    <th>date reported</th>
                    <th class="sorttable_nosort">start of narrative...</th>
                </tr>
            </thead>
            <tbody>
                {% for o in contact.observed_or_reported_ordered.reverse.all %}
                <tr>
                    <td>{{ o|link }}</td>
                    <td>{{ o.observer|link }}</td>
                    <td sorttable_customkey="{{ o.datetime_observed.sortkey }}">{% datetime_observed_display o.datetime_observed %}</td>
                    <td>{{ o.reporter|link }}</td>
                    <td sorttable_customkey="{{ o.datetime_reported.sortkey }}">{% datetime_observed_display o.datetime_reported %}</td>
                    <td>{{ o.narrative|truncatewords:9 }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <i>none</i>
        {% endif %}
    </div>
</div>
{% endblock %}

cetacean_incidents/templates/contacts/contact_detail.html
{% extends "contacts/contact_base.html" %}

{% block title %}{{ block.super }}: {{ contact }}{% endblock %}

{% block header %}
{{ block.super }}
{% if perms.contacts.change_contact %}
<div>
    <a href="{% url edit_contact contact.id %}">edit this contact</a>
</div>
{% endif %}
{% if perms.contacts.change_contact and perms.contacts.delete_contact %}
<script type="text/javascript">
    jQuery(document).ready(function(){
	    $('.accordion .header').click(function() {
		    $(this).next().toggle('fast');
		    return false;
	    }).next().hide();
    });
</script>
<div class="accordion">
    <div class="header">
        <a href="#">merge another contact into this one...</a>
    </div>
    <form action="{% url merge_contact contact.id %}" method="GET">
        <div style="margin-left:2em;">
            {{ merge_form.as_p }}
            <button type="submit">view merge</button>
        </div>
    </form>
</div>
{% endif %}
{% endblock %}


cetacean_incidents/templates/contacts/contact_list.html
{% extends "page.html" %}
{% load link_filter %}
{% load observation_extras %} {# for datetime_observed_display #}

{% block head %}
{{ block.super }}
<script type="text/javascript" src="{% url site-media path="sorttable/sorttable.js" %}"></script>
<link rel="stylesheet" type="text/css" href="{% url site-media path="sorttable/sorttable.css" %}">
{% endblock %}

{% block title %}{{ block.super }}: Contacts{% endblock %}

{% block header %}<h2>Contacts</h2>{% endblock %}

{% block content %}
<table class="layout">
    <tr>
        <td class="section">
            {% if contact_list %}
            <table class="sortable bordered">
                <colgroup span="1"></colgroup>
                <colgroup span="3"></colgroup>
                <colgroup span="3"></colgroup>
                <colgroup span="1"></colgroup>
                <thead style="vertical-align: top;">
                    <tr>
                        <th scope="col">contact</th>
                        <th scope="col"><abbr title="observations">obs.</abbr><br>count</th>
                        <th scope="col"><abbr title="observations">obs.</abbr><br>earliest</th>
                        <th scope="col"><abbr title="observations">obs.</abbr><br>latest</th>
                        <th scope="col">reports<br>count</th>
                        <th scope="col">reports<br>earliest</th>
                        <th scope="col">reports<br>latest</th>
                        <th scope="col">vessel<br>count</th>
                    </tr>
                </thead>
                <tbody>
                    {% for contact in contact_list %}
                    <tr>
                        <td scope="row"{% if contact.sort_name %} sorttable_customkey="{{ contact.sort_name }}"{% endif %}>
                            {{ contact|link }}
                        </td>
                        {% with contact.observed.count as obs_count %}
                        <td>
                            {{ obs_count }}
                        </td>
                        {% if obs_count %}
                        {% with contact.observed_ordered|first as first_o %}
                        <td sorttable_customkey="{{ first_o.datetime_observed.sortkey }}">
                            <a href="{{ first_o.get_absolute_url }}">
                                {% datetime_observed_display first_o.datetime_observed %}
                            </a>
                        </td>
                        {% endwith %}
                        {% with contact.observed_ordered.reverse|first as last_o %}
                        <td sorttable_customkey="{{ last_o.datetime_observed.sortkey }}">
                            <a href="{{ last_o.get_absolute_url }}">
                                {% datetime_observed_display last_o.datetime_observed %}
                            </a>
                        </td>
                        {% endwith %}
                        {% else %}
                        <td>-</td>
                        <td>-</td>
                        {% endif %}
                        {% endwith %}

                        <td>
                            {{ contact.reported.count }}
                        </td>
                        {% if contact.reported.count %}
                        {% with contact.reported_ordered|first as first_r %}
                        <td sorttable_customkey="{{ first_r.datetime_reported.sortkey }}">
                            <a href="{{ first_r.get_absolute_url }}">
                                {% datetime_observed_display first_r.datetime_reported %}
                            </a>
                        </td>
                        {% endwith %}
                        {% with contact.reported_ordered.reverse|first as last_r %}
                        <td sorttable_customkey="{{ last_r.datetime_reported.sortkey }}">
                            <a href="{{ last_r.get_absolute_url }}">
                                {% datetime_observed_display last_r.datetime_reported %}
                            </a>
                        </td>
                        {% endwith %}
                        {% else %}
                        <td>-</td>
                        <td>-</td>
                        {% endif %}
                        
                        <td>{{ contact.for_vessels.count }}</td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
            <i>No contacts yet!</i>
            {% endif %}
            {% if perms.contacts.add_contact %}
            <div>
                <a href="{% url create_contact %}">new contact</a>
            </div>
            {% endif %}
        </td>
    </tr>
</table>
{% endblock %}


cetacean_incidents/templates/contacts/contact_search.html
{% extends "page.html" %}
{% load link_filter %}

{% block title %}{{ block.super }}: Contact Search{% endblock %}

{% block header %}<h2>Contacts</h2>{% endblock %}

{% block content %}
{% if form.is_bound %}
<div style="text-align: center;">
{{ contact_count|default:"no" }} matching contact{{ contact_count|pluralize }}
</div>
{% with contacts as page %}
{% with 'the_form' as form_id %}
{% include "paging_form_include.html" %}
{% endwith %}
{% endwith %}

{% if contact_count > 0 %}
<table class="bordered">
    <thead>
        <tr>
            <th>link</th>
        </tr>
    </thead>
	{% for contact in contacts.object_list %}
	<tr>
	    <td>{{ contact|link }}</td>
    </tr>
    {% empty %}
    <tr><td colspan="5" style="text-align:center;"><i>no contacts</i></td></tr>
	{% endfor %}
</table>
{% endif %}
{% else %}
<p>
    click 'search' to see a list of contacts
</p>
{% endif %}
<form id="the_form" action="" method="get">
    <div class="section">
        <table>
            {{ form.as_table }}
            {{ paging_form.as_table }}
        </table>
        <button type="submit">search</button>
    </div>
</form>
{% endblock %}

cetacean_incidents/templates/contacts/create_contact.html
{% extends "page.html" %}

{% block title %}{{ block.super }}: new contact {% endblock %}

{% block header %}
<div>
    <h2>new contact</h2>
</div>
{% endblock %}

{% block content %}
<form action="" method="post">
{% csrf_token %}
{% include "contacts/change_contact_include.html" %}
<button type="submit">create contact</button>
</form>
{% endblock %}

cetacean_incidents/templates/contacts/edit_contact.html
{% extends "contacts/contact_base.html" %}
{% load html_filter %}

{% block title %}{{ block.super }}: editing {{ contact }}{% endblock %}

{% block header %}
{{ block.super }}
[editing]
{% endblock %}

{% block contact_fields %}
<form action="" method="post">
{% csrf_token %}
{% include "contacts/change_contact_include.html" %}
<button type="submit">save changes to {{ contact|html }}</button>
</form>
{% endblock %}

cetacean_incidents/templates/contacts/merge_contact.html
{% extends "merge_form/merge.html" %}
{% load merge_display %}

{% comment %}
This template is an amalgam of editing and viewing.
{% endcomment %}

{% block ids-dl %}
<dt><b>contact</b> names</dt><dd>merging {{ source.name|default:"<i>no name</i>" }} into {{ destination.name|default:"<i>no name</i>" }}</dd>
<dt><b>contact</b> local IDs</dt><dd>merging {{ source.id }} into {{ destination.id }}</dd>
{% endblock %}

{% block form_rows %}
{% display_merge_row destination source form 'name' %}
{% display_merge_row destination source form 'sort_name' %}
{% display_merge_yesnounk_row destination source form 'person' %}
{% display_merge_row destination source form 'phone' %}
{% display_merge_row destination source form 'email' %}
{% display_merge_row destination source form 'address' %}
{% display_merge_row destination source form 'notes' %}
{% endblock %}